# Generated by Django 5.0.6 on 2024-07-21 01:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recofy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="genres",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="preview_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
