# Generated by Django 5.0.6 on 2024-07-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recofy", "0002_alter_album_genres_alter_track_preview_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="is_playable",
            field=models.BooleanField(default=True),
        ),
    ]
