# Generated by Django 5.0.6 on 2024-07-21 04:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recofy", "0003_album_is_playable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="available_markets",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
